/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as NovaPrescricaoRouteImport } from './routes/nova-prescricao'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as IndexRouteImport } from './routes/index'

const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPrescricaoRoute = NovaPrescricaoRouteImport.update({
  id: '/nova-prescricao',
  path: '/nova-prescricao',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/nova-prescricao': typeof NovaPrescricaoRoute
  '/pacientes': typeof PacientesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/nova-prescricao': typeof NovaPrescricaoRoute
  '/pacientes': typeof PacientesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/nova-prescricao': typeof NovaPrescricaoRoute
  '/pacientes': typeof PacientesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historico' | '/nova-prescricao' | '/pacientes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historico' | '/nova-prescricao' | '/pacientes'
  id: '__root__' | '/' | '/historico' | '/nova-prescricao' | '/pacientes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  NovaPrescricaoRoute: typeof NovaPrescricaoRoute
  PacientesRoute: typeof PacientesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-prescricao': {
      id: '/nova-prescricao'
      path: '/nova-prescricao'
      fullPath: '/nova-prescricao'
      preLoaderRoute: typeof NovaPrescricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  NovaPrescricaoRoute: NovaPrescricaoRoute,
  PacientesRoute: PacientesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
